[options]
addons_path = C:\DEV\new\odoo\addons, C:\DEV\new\module
admin_passwd = 1234
db_host = localhost
db_maxconn = 64
db_name = False
db_password = 1234
db_port = 5432
db_user = admin
http_port = 8069
